[workspace]
name = "magpie"
channels = ["conda-forge"]
platforms = ["linux-64"]

[pypi-dependencies]
magpie = { path = ".", editable = true }

[environments]
default = { solve-group = "default" }
cuda = ["cuda"]

[feature.cuda.system-requirements]
cuda = "12"

[tasks]

[dependencies]
python = "3.12.*"
rust = ">=1.85.1,<1.86"

